# Form implementation generated from reading ui file './ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 545)
        MainWindow.setStyleSheet("background-color: #444444;\n"
"color: white;\n"
"font-family: Franklin Gothic Medium")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_label = QtWidgets.QLabel(parent=self.frame_2)
        self.search_label.setStyleSheet("font-size: 18pt;\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color:none;\n"
"border-bottom: 2px solid white;")
        self.search_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.search_label.setObjectName("search_label")
        self.verticalLayout_3.addWidget(self.search_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rfid_label = QtWidgets.QLabel(parent=self.frame_2)
        self.rfid_label.setMinimumSize(QtCore.QSize(0, 17))
        self.rfid_label.setMaximumSize(QtCore.QSize(16777215, 17))
        self.rfid_label.setStyleSheet("margin-left: 10px; \n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color:none;")
        self.rfid_label.setObjectName("rfid_label")
        self.verticalLayout_6.addWidget(self.rfid_label)
        self.rfid_input = QtWidgets.QLineEdit(parent=self.frame_2)
        self.rfid_input.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"padding: 2px 5px\n"
"")
        self.rfid_input.setObjectName("rfid_input")
        self.verticalLayout_6.addWidget(self.rfid_input)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.name_label = QtWidgets.QLabel(parent=self.frame_2)
        self.name_label.setMinimumSize(QtCore.QSize(0, 17))
        self.name_label.setMaximumSize(QtCore.QSize(16777215, 17))
        self.name_label.setStyleSheet("margin-left: 10px; \n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color:none;")
        self.name_label.setObjectName("name_label")
        self.verticalLayout_5.addWidget(self.name_label)
        self.name_input = QtWidgets.QLineEdit(parent=self.frame_2)
        self.name_input.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"padding: 2px 5px\n"
"")
        self.name_input.setObjectName("name_input")
        self.verticalLayout_5.addWidget(self.name_input)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.status_label = QtWidgets.QLabel(parent=self.frame_2)
        self.status_label.setMinimumSize(QtCore.QSize(0, 17))
        self.status_label.setMaximumSize(QtCore.QSize(16777215, 17))
        self.status_label.setStyleSheet("margin-left: 10px; \n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color:none;")
        self.status_label.setObjectName("status_label")
        self.verticalLayout_4.addWidget(self.status_label)
        self.status_box = QtWidgets.QComboBox(parent=self.frame_2)
        self.status_box.setStyleSheet("\n"
"\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"padding: 2px 5px;\n"
"")
        self.status_box.setObjectName("status_box")
        self.status_box.addItem("")
        self.status_box.addItem("")
        self.status_box.addItem("")
        self.verticalLayout_4.addWidget(self.status_box)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.interval_wigdet = QtWidgets.QTabWidget(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interval_wigdet.sizePolicy().hasHeightForWidth())
        self.interval_wigdet.setSizePolicy(sizePolicy)
        self.interval_wigdet.setMinimumSize(QtCore.QSize(0, 100))
        self.interval_wigdet.setMaximumSize(QtCore.QSize(16777215, 100))
        self.interval_wigdet.setStyleSheet("QTabWidget{\n"
"    margin: 4px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane { \n"
"    border-top: 2px solid white;\n"
"    margin-top: 4px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*11111111111111111111*/\n"
"\n"
"\n"
"QTabBar::tab{\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px 15px;\n"
"    margin: 0 5px;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background-color: rgb(31, 184, 107);\n"
"}\n"
"\n"
"QTabBar::tab:selected:hover{\n"
"    background-color: rgba(31, 184, 107, 95);\n"
"}\n"
"\n"
"QTabBar::tab:!selected{\n"
"    background-color: none;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover{\n"
"    background-color: none;\n"
"    border: 1px solid rgba(255,255,255, 80);\n"
"}\n"
"\n"
"")
        self.interval_wigdet.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.interval_wigdet.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.interval_wigdet.setUsesScrollButtons(True)
        self.interval_wigdet.setDocumentMode(False)
        self.interval_wigdet.setObjectName("interval_wigdet")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.interval_box = QtWidgets.QComboBox(parent=self.tab)
        self.interval_box.setStyleSheet("\n"
"QComboBox {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"padding: 2px 5px;\n"
"}\n"
"\n"
"")
        self.interval_box.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtTop)
        self.interval_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.interval_box.setObjectName("interval_box")
        self.interval_box.addItem("")
        self.interval_box.addItem("")
        self.interval_box.addItem("")
        self.gridLayout_2.addWidget(self.interval_box, 0, 0, 1, 1)
        self.interval_wigdet.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ot_label = QtWidgets.QLabel(parent=self.tab_2)
        self.ot_label.setStyleSheet("margin-left: 10px; \n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color:none;")
        self.ot_label.setObjectName("ot_label")
        self.horizontalLayout.addWidget(self.ot_label)
        self.datetime_from = QtWidgets.QDateTimeEdit(parent=self.tab_2)
        self.datetime_from.setStyleSheet("\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"padding: 2px 5px;\n"
"\n"
"\n"
"")
        self.datetime_from.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.datetime_from.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.datetime_from.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.datetime_from.setObjectName("datetime_from")
        self.horizontalLayout.addWidget(self.datetime_from)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.do_label = QtWidgets.QLabel(parent=self.tab_2)
        self.do_label.setStyleSheet("margin-left: 10px; \n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color:none;")
        self.do_label.setObjectName("do_label")
        self.horizontalLayout_2.addWidget(self.do_label)
        self.datetime_to = QtWidgets.QDateTimeEdit(parent=self.tab_2)
        self.datetime_to.setStyleSheet("\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"padding: 2px 5px;\n"
"\n"
"\n"
"")
        self.datetime_to.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.datetime_to.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.datetime_to.setSpecialValueText("")
        self.datetime_to.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.datetime_to.setObjectName("datetime_to")
        self.horizontalLayout_2.addWidget(self.datetime_to)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.interval_wigdet.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.interval_wigdet)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.search_button = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy)
        self.search_button.setMinimumSize(QtCore.QSize(0, 29))
        self.search_button.setMaximumSize(QtCore.QSize(16777215, 29))
        self.search_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(31, 184, 107);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(31, 184, 107, 95);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(31, 184, 107, 85);\n"
"}\n"
"\n"
"")
        self.search_button.setObjectName("search_button")
        self.verticalLayout_3.addWidget(self.search_button)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.table_view = QtWidgets.QTableView(parent=self.centralwidget)
        self.table_view.setObjectName("table_view")
        self.horizontalLayout_3.addWidget(self.table_view)
        self.horizontalLayout_3.setStretch(0, 5)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 24))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_3.setStyleSheet("border: 1px solid white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.status_label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.status_label_2.setGeometry(QtCore.QRect(330, -10, 141, 41))
        self.status_label_2.setObjectName("status_label_2")
        self.status_color_label = QtWidgets.QLabel(parent=self.frame_3)
        self.status_color_label.setGeometry(QtCore.QRect(410, 0, 51, 21))
        self.status_color_label.setObjectName("status_color_label")
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 20))
        self.menubar.setObjectName("menubar")
        self.menudddddddddddddddddddddddd = QtWidgets.QMenu(parent=self.menubar)
        self.menudddddddddddddddddddddddd.setObjectName("menudddddddddddddddddddddddd")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtGui.QAction(parent=MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtGui.QAction(parent=MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtGui.QAction(parent=MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtGui.QAction(parent=MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtGui.QAction(parent=MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtGui.QAction(parent=MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtGui.QAction(parent=MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtGui.QAction(parent=MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtGui.QAction(parent=MainWindow)
        self.action_11.setObjectName("action_11")
        self.menudddddddddddddddddddddddd.addAction(self.action_3)
        self.menudddddddddddddddddddddddd.addAction(self.action_5)
        self.menudddddddddddddddddddddddd.addAction(self.action_11)
        self.menudddddddddddddddddddddddd.addAction(self.action_7)
        self.menu.addAction(self.action_6)
        self.menu.addAction(self.action_8)
        self.menu.addAction(self.action_9)
        self.menu.addAction(self.action_10)
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menubar.addAction(self.menudddddddddddddddddddddddd.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.interval_wigdet.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rfid_input, self.name_input)
        MainWindow.setTabOrder(self.name_input, self.status_box)
        MainWindow.setTabOrder(self.status_box, self.interval_wigdet)
        MainWindow.setTabOrder(self.interval_wigdet, self.datetime_from)
        MainWindow.setTabOrder(self.datetime_from, self.datetime_to)
        MainWindow.setTabOrder(self.datetime_to, self.search_button)
        MainWindow.setTabOrder(self.search_button, self.table_view)
        MainWindow.setTabOrder(self.table_view, self.interval_box)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_label.setText(_translate("MainWindow", "Поиск"))
        self.rfid_label.setText(_translate("MainWindow", "RFID код"))
        self.name_label.setText(_translate("MainWindow", "ФИО"))
        self.status_label.setText(_translate("MainWindow", "Статус"))
        self.status_box.setItemText(0, _translate("MainWindow", "Нет значения"))
        self.status_box.setItemText(1, _translate("MainWindow", "Вход"))
        self.status_box.setItemText(2, _translate("MainWindow", "Выход"))
        self.interval_box.setItemText(0, _translate("MainWindow", "Нет значения"))
        self.interval_box.setItemText(1, _translate("MainWindow", "Вход"))
        self.interval_box.setItemText(2, _translate("MainWindow", "Выход"))
        self.interval_wigdet.setTabText(self.interval_wigdet.indexOf(self.tab), _translate("MainWindow", "Интервал"))
        self.ot_label.setText(_translate("MainWindow", "От"))
        self.do_label.setText(_translate("MainWindow", "До"))
        self.interval_wigdet.setTabText(self.interval_wigdet.indexOf(self.tab_2), _translate("MainWindow", "Дата"))
        self.search_button.setText(_translate("MainWindow", "Найти"))
        self.status_label_2.setText(_translate("MainWindow", "СТАТУС"))
        self.status_color_label.setText(_translate("MainWindow", "TextLabel"))
        self.menudddddddddddddddddddddddd.setTitle(_translate("MainWindow", "Файл"))
        self.menu.setTitle(_translate("MainWindow", "Изменить"))
        self.menu_2.setTitle(_translate("MainWindow", "Добавить"))
        self.menu_3.setTitle(_translate("MainWindow", "Вид"))
        self.action.setText(_translate("MainWindow", "Добавить пользователя"))
        self.action_2.setText(_translate("MainWindow", "Добавить несколько"))
        self.action_3.setText(_translate("MainWindow", "Обновить данные"))
        self.action_4.setText(_translate("MainWindow", "Изменить"))
        self.action_5.setText(_translate("MainWindow", "Сохранить"))
        self.action_6.setText(_translate("MainWindow", "Добавить запись"))
        self.action_7.setText(_translate("MainWindow", "Выход"))
        self.action_8.setText(_translate("MainWindow", "Редактировать запись"))
        self.action_9.setText(_translate("MainWindow", "Удалить запись"))
        self.action_10.setText(_translate("MainWindow", "Очистить поля поиска"))
        self.action_11.setText(_translate("MainWindow", "Настройки"))
